CIRCUITPY_PYSTACK_SIZE = 4608

[BERYLLIUM]
setup = true

fs_label = "BERYLLIUM"

serial_console_enabled = true
usb_msc_available = true
usb_hid_available = true
usb_midi_available = true
wifi_available = true
ble_available = false
blc_available = false
usb_msc_enabled = false
usb_hid_enabled = false
usb_midi_enabled = false

ledtype = "generic"
led = "LED"

DEBUG = false

[IWD]
#Network2 = "password2"

[IWD-AP]
SSID = "beryllium-ap"
PASSWD = "CHANGEME WIFI PASSWORD"
